# Generated by Django 2.2.5 on 2019-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(max_length=32)),
                ('mchId', models.CharField(max_length=32)),
                ('deviceInfo', models.CharField(max_length=32)),
                ('nonceStr', models.CharField(max_length=32)),
                ('sign', models.CharField(max_length=32, null=True)),
                ('signType', models.CharField(max_length=32)),
                ('body', models.CharField(max_length=128)),
                ('outTradeNo', models.CharField(max_length=32)),
                ('totalFee', models.IntegerField()),
                ('spBillCreateIp', models.CharField(max_length=64)),
                ('timeStart', models.CharField(max_length=14)),
                ('timeExpire', models.CharField(max_length=14)),
                ('notifyUrl', models.CharField(max_length=256)),
                ('tradeType', models.CharField(max_length=16)),
                ('openId', models.CharField(max_length=128)),
                ('returnCode', models.CharField(max_length=16, null=True)),
                ('returnMsg', models.CharField(max_length=128, null=True)),
                ('resultCode', models.CharField(max_length=16, null=True)),
                ('errCode', models.CharField(max_length=32, null=True)),
                ('errCodeDesc', models.CharField(max_length=128, null=True)),
                ('prepayId', models.CharField(max_length=64)),
            ],
        ),
    ]
