# Generated by Django 2.2.5 on 2019-09-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram_api', '0003_auto_20190923_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payorder',
            name='openId',
        ),
        migrations.AddField(
            model_name='payorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
